### ISSUE TITLE
The idea is not compatible with google cloud

### ISSUE THREAD

**Issue by fssrepository** [wmnnd/nginx-certbot#111]
I have a compute engine, i would like to manage my certificate as Google Managed certificate is announced to be free, but there are services required to make it working. (doubling the expenses)

In Compute engine you can't run scripts, you might be able to run inside the docker container, however you can't say docker-compose inside the container and there are other stuff.

Major cloud providers are doing the same i feel, allow_exec rule will be disabled.

**Comment by wmnnd** [comment]
Then you might want to look for something like Traefik. Check out my article on getting HTTPS to work with Traefik:
https://pentacent.com/blog/lets-encrypt-for-your-docker-app-in-less-than-5-minutes

**Comment by fssrepository** [comment]
The problem is, that it's not compatible with the big 3, thus it's not that helpfull.

You can improve it, to wrap up the scripts into a docker container, that it will be compatible.

I'm not sure, what will happen with my domain, if i need to reissue the certificate, as i'm going to leave GCP after the trial period.

Using the platform sucks.

Any idea?

Can i reissue the certificate, or the google managed certificate will block me to migrate to different provider?

**Comment by fssrepository** [comment]
Can i reissue the certificate, or the google managed certificate will block
me to migrate to different provider?

**Comment by wmnnd** [comment]
This script is not made for use with these platforms. This is why I would recommend using Traefik in these situations.
Check out the article I linked above for a how-to :slightly_smiling_face: 
Besides that, I don’t see how having a certificate from Google could prevent you from getting another certificate from another provider.

**Comment by fssrepository** [comment]
Reissueing certificate is not that easy, if GCP hides everything from you.

Stupid question, for the same domain, if i have one certificate for a
domain, can i generate a new one with your scripts, or i need to release
the old one or reissue?

**Comment by wmnnd** [comment]
Since this script gets certificates from Let’s Encrypt, having previous certificates from GCP will not impact them.
