### ISSUE TITLE
Don't affect linked containers

### ISSUE THREAD

**Issue by darlandieterich** [wmnnd/nginx-certbot#18]
When have multiples container with 'links' in docker-compose don't have necessary recreat all containers, only the nginx. If you find it interesting, you can add parameter --no-deps in step 'Starting nginx', with purpose to don't recreat the linked containers.

**Comment by wmnnd** [comment]
Thank you for the suggestion, @darlandieterich! I have now added this parameter to the [2.x branch](https://github.com/wmnnd/nginx-certbot/tree/2.x). Could you give it a try and let me know if it works for you?
