### ISSUE TITLE
Firewall problem

### ISSUE THREAD

**Issue by svliantiss** [wmnnd/nginx-certbot#22]
# Problem
- When trying the script it doesn't work because of a firewall problem
- How do I adjust the script for multiple domains and subdomains

## Output of running the script:
svl@Dinkleberg:~/projects/dinkleberg$ sudo ./init-letsencrypt.sh
Existing data found for dinkleberg.weslynouse.com. Continue and replace existing certificate? (y/N) y
### Creating dummy certificate for dinkleberg.weslynouse.com ...
Generating a RSA private key
......+++++
.......................................+++++
writing new private key to '/etc/letsencrypt/live/dinkleberg.weslynouse.com/privkey.pem'
-----
failed to resize tty, using default size

### Starting nginx ...
ERROR: No such service: nginx

### Requesting Let's Encrypt certificate for dinkleberg.weslynouse.com ...
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for dinkleberg.weslynouse.com
http-01 challenge for www.dinkleberg.weslynouse.com
Using the webroot path /var/www/certbot for all unmatched domains.
Waiting for verification...
Challenge failed for domain dinkleberg.weslynouse.com
Challenge failed for domain www.dinkleberg.weslynouse.com
http-01 challenge for dinkleberg.weslynouse.com
http-01 challenge for www.dinkleberg.weslynouse.com
Cleaning up challenges
Some challenges have failed.

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: dinkleberg.weslynouse.com
   Type:   connection
   Detail: Fetching
   http://dinkleberg.weslynouse.com/.well-known/acme-challenge/-j9dgHaNtSanBoNa8fPhUlxr7OsgNWwDPV18N_PhRdU:
   Timeout during connect (likely firewall problem)

   Domain: www.dinkleberg.weslynouse.com
   Type:   connection
   Detail: Fetching
   http://www.dinkleberg.weslynouse.com/.well-known/acme-challenge/PWABzad3TQboWDKM__QNLkVJuMloybNn0tSChd95tmo:
   Timeout during connect (likely firewall problem)

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.

### Reloading nginx ...
ERROR: No such service: nginx
svl@Dinkleberg:~/projects/dinkleberg$
svl@Dinkleberg:~/projects/dinkleberg$ sudo ./init-letsencrypt.sh | cat >> output.txt
Existing data found for dinkleberg.weslynouse.com. Continue and replace existing certificate? (y/N) y
ERROR: No such service: nginx
ERROR: No such service: nginx
svl@Dinkleberg:~/projects/dinkleberg$ cat output.txt
### Creating dummy certificate for dinkleberg.weslynouse.com ...
Generating a RSA private key
........+++++
..+++++
writing new private key to '/etc/letsencrypt/live/dinkleberg.weslynouse.com/privkey.pem'
-----

### Requesting Let's Encrypt certificate for dinkleberg.weslynouse.com ...
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for dinkleberg.weslynouse.com
http-01 challenge for www.dinkleberg.weslynouse.com
Using the webroot path /var/www/certbot for all unmatched domains.
Waiting for verification...
Challenge failed for domain dinkleberg.weslynouse.com
Challenge failed for domain www.dinkleberg.weslynouse.com
http-01 challenge for dinkleberg.weslynouse.com
http-01 challenge for www.dinkleberg.weslynouse.com
Cleaning up challenges
Some challenges have failed.

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: dinkleberg.weslynouse.com
   Type:   connection
   Detail: Fetching
   http://dinkleberg.weslynouse.com/.well-known/acme-challenge/Yv9Mj-jafT3Kq_TVKu06eMUHjAIHB-mq427OyWG4NVo:
   Timeout during connect (likely firewall problem)

   Domain: www.dinkleberg.weslynouse.com
   Type:   connection
   Detail: Fetching
   http://www.dinkleberg.weslynouse.com/.well-known/acme-challenge/RK8Kq0MnfD-C3wT46h9fyPDoVgtPa9NP9J2hYYY9hnA:
   Timeout during connect (likely firewall problem)

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.

## app.conf settings:
svl@Dinkleberg:~/projects/dinkleberg$ cat data/nginx/app.conf
server {
    listen 80;
    server_name dinkleberg.weslynouse.com;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name dinkleberg.weslynouse.com;
    server_tokens off;

    ssl_certificate /etc/letsencrypt/live/dinkleberg.weslynouse.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dinkleberg.weslynouse.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass  http://dinkleberg.weslynouse.com;
        proxy_set_header    Host                $http_host;
        proxy_set_header    X-Real-IP           $remote_addr;
        proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
    }
}

## docker-compose.yml settings:

svl@Dinkleberg:~/projects/dinkleberg$ cat docker-compose.yml
version: '3'

services:
  base:
    build: ./base
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot:latest
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

**Comment by wmnnd** [comment]
Hey there,

it seems like you’ve modified the docker-compose file in such a way that there is no container called `nginx`.
Without that, the script will not work.
