### ISSUE TITLE
There were too many requests of a given type :: Error creating new order :: too many certificates already issued for exact set of domains

### ISSUE THREAD

**Issue by thunpisit** [wmnnd/nginx-certbot#27]
I encounter after changing the staging from 1 to 0, do you happen to know how to fix this because I only request once.

```
### Requesting Let's Encrypt certificate for snickies.com ...
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Obtaining a new certificate
An unexpected error occurred:
There were too many requests of a given type :: Error creating new order :: too many certificates already issued for exact set of domains: snickies.com,www.snickies.com: see https://letsencrypt.org/docs/rate-limits/
Please see the logfiles in /var/log/letsencrypt for more details.
```

**Comment by thunpisit** [comment]
I found the problem that I did request it before with different tutorial before yours and I hit 5 request after tried yours, guess I have to wait for a week.

**Comment by wmnnd** [comment]
In the future, when experimenting with Let’s Encrypt, I’d recommend using staging mode where these limits don’t exist.

**Comment by Albinzr** [comment]
When using staging Im getting an not secure while calling api, and when I changed staging to prod (1 => 0) script says everything is success but still seeing not secure while calling domain.

when i removed and did a fresh execution it started working then when i switched to staging again and came back to prod im facing same issue can you help
