### ISSUE TITLE
Workflow for adding new certificates without generating all the certificates

### ISSUE THREAD

**Issue by almarrr** [wmnnd/nginx-certbot#30]
When I run init-letsencrypt.sh it generates new certificates for all my websites. Is it possible to check every certificate and skip it when it's already generated?

**Comment by wagnerdelima** [comment]
@almarrr once init-letsencrypt.sh is run it will use let's encrypt to generate a new certificate. If the certificate is not up to renewal it won't be renewed. You don't have to worry about skipping the certificates that are generated already. It's done automatically for you.

**Comment by almarrr** [comment]
@wagnerdelima So, what you mean is I can run init-letsencrypt.sh every time when I've added a new (sub)domain without getting in trouble of the letsencrypt rate limit? That would be awesome.

**Comment by wagnerdelima** [comment]
@almarrr you should request a new certificate every 6 hours without a problem. If you try to request more often you will fall under rate limiting. 
You should also read this: https://letsencrypt.org/docs/rate-limits/. It's very informative!
