### ISSUE TITLE
What if the docker-compose file has a different name

### ISSUE THREAD

**Issue by knasti** [wmnnd/nginx-certbot#34]
Hi Philipp,

I followed your tutorial about getting the certificates up and running, and it's great. But I spent quite some time figuring out why it did not work for me initially. Turned out that it was because I have two different docker-compose files, "docker-compose.yml" for development and "docker-compose.prod.yml" for production. This made the init-letsencrypt.sh fail, as nginx and certbot does not exist in my development environment. So I had to change all the "docker-compose" commands to "docker-compose -f docker-compose.prod.yml" in init-letsencrypt.sh.

So I would propose that it is briefly mentioned alongside the following section to save others the headache I got, what's your thoughts?

> Edit the script to add in your domain(s) and your email address. If you’ve changed the directories of the shared Docker volumes, make sure you also adjust the data_path variable as well.

**Comment by wmnnd** [comment]
Hey @knasti, thank you for the suggestion! I have included this feature in the [2.x branch](https://github.com/wmnnd/nginx-certbot/tree/2.x). You can now call `./init-letsencrypt.sh -f you-docker-compose.yml` :tada:
