### ISSUE TITLE
Why use "sleep 6h & wait $${!}"?

### ISSUE THREAD

**Issue by walkerneo** [wmnnd/nginx-certbot#36]
In the service startup commands, there is:
`command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"`

Two questions:

- Why are there two dollar signs? Is the first one needed to escape the second for some reason?
- Why not just do "sleep 6h" directly instead of sleep and then wait?

**Comment by franckadil** [comment]
I had the same question ... I am still searching.

**Comment by walkerneo** [comment]
I asked here: https://stackoverflow.com/questions/56981892/why-do-sleep-wait-in-bash. I haven't looked into the answer yet, but it seems correct.

**Comment by wmnnd** [comment]
@walkerneo Thank you for your question! The intention of this odd entrypoint is to allow a quick shutdown of the container if it’s supposed to be terminated. When you only use `sleep`, it won’t exit immediately after receiving the termination signal.
