### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by Nojusle** [wmnnd/nginx-certbot#38]
one of the links used in init-letsencrypt.sh is broken and returns 404: Not Found, because of that script no longer works.

file: init-letsencrypt.sh
`curl -s https://raw.githubusercontent.com/certbot/certbot/master/certbot-nginx/certbot_nginx/options-ssl-nginx.conf > "$data_path/conf/options-ssl-nginx.conf"
`

the link:
[https://raw.githubusercontent.com/certbot/certbot/master/certbot-nginx/certbot_nginx/options-ssl-nginx.conf](https://raw.githubusercontent.com/certbot/certbot/master/certbot-nginx/certbot_nginx/options-ssl-nginx.conf)

**Comment by Captain-Oski** [comment]
I back this issue !
