### ISSUE TITLE
certificate not seruce chrome?

### ISSUE THREAD

**Issue by ncc0706** [wmnnd/nginx-certbot#4]
![image](https://user-images.githubusercontent.com/11310593/50813859-aea7f680-1352-11e9-855a-05bce6f6929f.png)

**Comment by ncc0706** [comment]
domains=(arukas.cf www.arukas.cf api.arukas.cf) 
cause certificate not seruce

**Comment by wmnnd** [comment]
Hey there, it seems like the validation process might not have worked. What’s the output you get when running `init-letsencrypt`?

**Comment by wmnnd** [comment]
It also seems like you’ve modified a bunch of stuff in the `init-letsencrypt` script. Could you try using an unmodified version and just add your domains?

**Comment by ncc0706** [comment]
support combine subdomain into a single certificate?

**Comment by wmnnd** [comment]
Yes, if you specify multiple domains, they will all be combined in one certificate.

**Comment by ncc0706** [comment]
@wmnnd Thanks very much. like this 
https://spring-cloud.ml/
https://www.spring-cloud.ml/
https://api.spring-cloud.ml/
