### ISSUE TITLE
How to init cert on local machine?

### ISSUE THREAD

**Issue by a-klimashevsky** [wmnnd/nginx-certbot#40]
Im testing your script to build my react app. 
Is it possible to setup certbot on local machine (or CI server)?
Currently I'v got error `Challenge failed for domain MY_DOMAIN`

`IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: MY_DOMAIN
   Type:   unauthorized
   Detail: Invalid response from
   https://MY_DOMAIN/.well-known/acme-challenge/eGeqlLCWOxrzVHX-QrW8kUvkfS7iE9E0ck2vzTdDFSk
   [194.61.1.107]: "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta
   charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot
   GET /.well-known/"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.
`

**Comment by dimkasta** [comment]
You would have to somehow publish your local machine or ci server to the internet, so that the acme challenge can be completed by the letsencrypt service

**Comment by wmnnd** [comment]
@a-klimashevsky: Like @dimkasta said, you cannot get the Let’s Encrypt certificate on your local machine because LE needs to be able to connect to your machine in order to issue the certificate.

**Comment by theweiweiway** [comment]
@dimkasta @wmnnd 
If i were to go through the route of hosting my server on AWS, does this mean i  **must** run the init-letsencrypt.sh script from AWS's virtual machine? Or is there a way to do it from my local machine?

Thanks for the amazing article and repository btw! This helped me out tremendously
