### ISSUE TITLE
Attempting to renew cert (domain.com) from /etc/letsencrypt/renewal/domain.com.conf produced an unexpected error: 

### ISSUE THREAD

**Issue by darlandieterich** [wmnnd/nginx-certbot#41]
When expire the cert, the certbot try renew them and show this error:

```
Cert is due for renewal, auto-renewing...
Non-interactive renewal: random delay of 190 seconds
Plugins selected: Authenticator webroot, Installer None
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for domain.com
Cleaning up challenges
Attempting to renew cert (domain.com) from /etc/letsencrypt/renewal/domain.com.conf produced an unexpected error: Missing command line flag or config entry for this setting:
Input the webroot for domain.com:. Skipping.
```

This is working but when expired not renew more...
I suppose the problem is with webroot dir

**Comment by darlandieterich** [comment]
The error occurs because I have 2 domains, so I solved it like this:

In `/etc/letsencrypt/renewal/domain.com`
I force this `domain.com = /var/www/certbot` in last line of file

:)

**Comment by ahalma** [comment]
I ran into the same issue...

Instead of modifying the 'internal' `/etc/letsencrypt/renewal/domain.com`, I solved it by adding the `--webroot-path` argument in the docker-compose file...

```
entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot-path /var/www/certbot; sleep 12h & wait $${!}; done;'"
```
