### ISSUE TITLE
Problem on .tirol Domain

### ISSUE THREAD

**Issue by naschidaniel** [wmnnd/nginx-certbot#42]
Hello,

i have installed you script and it works perfekt for my .info domain. The problem on the .tirol domain is that the folder structere for the certificate is not created.

I have used exactly the same file with the difference.

The failor is:
### Reloading nginx ...
2019/09/11 19:43:43 [emerg] 9#9: cannot load certificate "/etc/letsencrypt/live/moses.tirol/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/moses.tirol/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/moses.tirol/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/moses.tirol/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)

**Comment by naschidaniel** [comment]
Problem solved. it has nothing to do with your script

**Comment by devkea** [comment]
But how did you fix it?
