### ISSUE TITLE
Where shall I put the html content ?

### ISSUE THREAD

**Issue by danielporto** [wmnnd/nginx-certbot#43]
Sorry if this is a super dumb question but I failed to find where shall i put the html pages...
I tried on ./data/certbot/www after generating the certificates.

When I try to open in the browser it fails with "try to clean your cookies". I tried with 3 different web browsers and in incognito mode.
When I use curl to https site I get a 301 site moved permanently.
I reviewed all files, even carefully compared with the git repo... 
Do you have any idea what's going on?
Site scores A at SSL Labs test anyways... but no webpage is shown.

**Comment by rafaeljpc** [comment]
Hello,

Any progress for this issue?

**Comment by SoltauFintel** [comment]
Here's my solution:

Go to the folder where's your docker-compose.yml file

`      - .:/usr/share/nginx/html`
Add this line to the 1st volumes section of docker-compose.yml. Use the right indent.

`echo "letsencrypt nginx works" > index.html`

`cd data/nginx`

Edit 2nd server section of app.conf. First, remove the proxy_pass line.

`root /usr/share/nginx/html;`
Second, add this line. Save app.conf.

`cd ../..`

`docker-compose down` (if necessary)

`docker-compose up -d`

Now call https://yourdomain.com/index.html in your browser. Works.

Troubleshooting

Use "docker logs _{nginx-container-name}_" to find the problem
or use "docker exec -it _{nginx-container-name}_ /bin/sh" to go into the running container and look for the files.

**Comment by wmnnd** [comment]
Hey @danielporto & @rafaeljpc: Thank you for your question.
The `/data/certbot/www` folder is only used by certbot and you should not put your own content in there if you want to serve static files.
The idea here is to modify `app.conf` and replace the bit that is a `proxy_pass` to `example.org` with your own configuration.
You could either modify the `proxy_pass` directive to proxy a locally running server or you add your local folder as a volume to `docker-compose.yml` and then configure nginx to serve those files.
