### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by alphat5** [wmnnd/nginx-certbot#46]
Hi, I finished following your tutorial but when I go to my URL, I get the ERR_TOO_MANY_REDIRECTS issue. Did someone already encounter this issue and could fix it?

I don't know which files I should share with you, so don't hesitate to ask ;).

Thanks in advance,
Best,

**Comment by Arkansio** [comment]
Hi,

I have the same problem.. Did you solve the problem @alphat5  ?

Thanks

**Comment by alphat5** [comment]
Hi @Arkansio,

I could not figure the issue out. So I used NGINX-PROXY (https://github.com/jwilder/nginx-proxy) with the let's Encrypt companion (you will find it in the readme).

Best,

**Comment by silentw** [comment]
#54

**Comment by ugGit** [comment]
Checkout the pull request mentioned above by @silentw. It's easily fixed by changing `proxy_pass http://...` to `proxy_pass https://` in `data/nginx/app.conf`.
