### ISSUE TITLE
Wildcard certificate?

### ISSUE THREAD

**Issue by rlaferla** [wmnnd/nginx-certbot#49]
How do you create a wildcard certificate for all subdomains in a domain? 

BTW - There is another issue but it's about multiple specified domains and not wildcards.

**Comment by wmnnd** [comment]
This script uses Let’s Encrypt’s `HTTP-01` challenge. Unfortunately, this makes it impossible to request wildcard certificates. Those are only available through the `DNS-01` challenge.
You can learn more about the different challenge types [here](https://letsencrypt.org/docs/challenge-types/).

**Comment by rlaferla** [comment]
Take a look at this article.  This developer created a certbot script for wildcards:

https://www.bennadel.com/blog/3420-obtaining-a-wildcard-ssl-certificate-from-letsencrypt-using-the-dns-challenge.htm

**Comment by wmnnd** [comment]
Using the DNS challeng requires you to manually set up the DNS records to get the certificate. And then you don’t need nginx running in order to do the HTTP challenge – thus making this script unnecessary :)
