### ISSUE TITLE
Never reuse dhparams

### ISSUE THREAD

**Issue by vbrandl** [wmnnd/nginx-certbot#5]
The init script will download known dhparams from GitHub (https://github.com/wmnnd/nginx-certbot/blob/master/init-letsencrypt.sh#L21). You must never, ever reuse dhparams but generate new params on each machine and keep them secret.

Here is how you would generate new dhparams: `openssl dhparam -out dhparam.pem 4096` (this might take some time)

**Comment by wmnnd** [comment]
Thank you for opening this issue!

It is my understanding that Diffie-Hellman parameters can be safely reused which is also why Certbot have included one in their Git repository.

You can check out the discussion in the Certbot issues here:
https://github.com/certbot/certbot/issues/374#issuecomment-114236157

But I’d be happy to accept a PR that adds a (non-default) flag for creating your own dhparam.pem.

**Comment by vbrandl** [comment]
Ah sorry. Seems I got that one wrong.
