### ISSUE TITLE
Did not work with multiple domains; here's a fix

### ISSUE THREAD

**Issue by dchersey** [wmnnd/nginx-certbot#6]
I did not find that the init script worked if I had multiple domains; also I found that I needed to parameterize it to reflect staging/production environments that use different docker-compose files and domains. 

Here's what I came up with -- if you like I can make a PR. 

```bash
#!/bin/bash
die () {
    echo >&2 "$@"
    exit 1
}

[ "$#" -ge 2 ] || die "usage: init-letsencrypt.sh [staging | production] <domain1 domain2 ...> "

domains=(${@:2})
rsa_key_size=4096
data_path="/etc/certbot"
email="david@leapforward.us" # Adding a valid address is strongly recommended
staging=0 # Set to 1 if you're testing your setup to avoid hitting request limits


if [ -d "$data_path/conf/live/" ]; then
  read -p "Existing data found. Continue and replace existing certificates? (y/N) " decision
  if [ "$decision" != "Y" ] && [ "$decision" != "y" ]; then
    exit
  fi
fi

if [ ! -e "$data_path/conf/options-ssl-nginx.conf" ] || [ ! -e "$data_path/conf/ssl-dhparams.pem" ]; then
  echo "### Downloading recommended TLS parameters ..."
  mkdir -p "$data_path/conf"
  curl -s https://raw.githubusercontent.com/certbot/certbot/master/certbot-nginx/certbot_nginx/options-ssl-nginx.conf > "$data_path/conf/options-ssl-nginx.conf"
  curl -s https://raw.githubusercontent.com/certbot/certbot/master/certbot/ssl-dhparams.pem > "$data_path/conf/ssl-dhparams.pem"
  echo
fi

for domain in "${domains[@]}"; do
  echo "### Removing old certificate for $domain ..."
  docker-compose -f docker-compose.yml -f docker-compose.$1.yml run --rm --entrypoint "\
    rm -Rf /etc/letsencrypt/live/$domain && \
    rm -Rf /etc/letsencrypt/archive/$domain && \
    rm -Rf /etc/letsencrypt/renewal/$domain.conf" certbot
  echo
done

for domain in "${domains[@]}"; do
  echo "### Creating dummy certificate for $domain ..."
  path="/etc/letsencrypt/live/$domain"
  mkdir -p "$data_path/conf/live/$domain"
  docker-compose -f docker-compose.yml -f docker-compose.$1.yml run --rm --entrypoint "\
    openssl req -x509 -nodes -newkey rsa:1024 -days 1\
      -keyout "$path/privkey.pem" \
      -out "$path/fullchain.pem" \
      -subj '/CN=localhost'" certbot
  echo
done

echo "### Starting nginx ..."
docker-compose -f docker-compose.yml -f docker-compose.$1.yml up --force-recreate -d nginx
echo

for domain in "${domains[@]}"; do
  echo "### Removing dummy certificate for $domain ..."
  docker-compose -f docker-compose.yml -f docker-compose.$1.yml run --rm --entrypoint "\
    rm -Rf /etc/letsencrypt/live/$domain" certbot
  echo
done

echo "### Requesting Let's Encrypt certificates ..."

# Select appropriate email arg
case "$email" in
  "") email_arg="--register-unsafely-without-email" ;;
  *) email_arg="--email $email" ;;
esac

# Enable staging mode if needed
if [ $staging != "0" ]; then staging_arg="--staging"; fi

for domain in "${domains[@]}"; do
  docker-compose -f docker-compose.yml -f docker-compose.$1.yml run --rm --entrypoint "\
    certbot certonly --webroot -w /var/www/certbot \
      $staging_arg \
      $email_arg \
      -d $domain \
      --rsa-key-size $rsa_key_size \
      --agree-tos \
      --force-renewal" certbot
  echo
done

echo "### Reloading nginx ..."
docker-compose -f docker-compose.yml -f docker-compose.$1.yml exec nginx nginx -s reload
```

**Comment by wmnnd** [comment]
I like the idea of calling the script with the domains as parameters. That’s so much more elegant!

Instead of using `staging` and `production` as arguments, I would suggest a `--staging` switch, since `production`doesn't seem to do anything.

**Comment by bjornol** [comment]
Thanks for sharing this. Was looking to add the same. Worked like a charm

**Comment by dchersey** [comment]
The 2nd argument (production | staging) determines which `docker-compose.$1` file is used later in the script.  So that works if that's how you organize your docker-composes, otherwise the user has to modify accordingly.  I'll create a PR shortly...

**Comment by pablodiegoss** [comment]
I was just working with this and came to a really close solution, came here to check for any pending PRs or issues. 
Nice dude, this will help a lot of people o/

**Comment by wmnnd** [comment]
@dchersey I think it would be nicer to be more explicit here. So I suggest adding an `-f` parameter that allows specifying the actual `docker-compose.yml` path.

**Comment by romfrolov** [comment]
Well, it wasn't so flawless for me. For the first domain everything worked smoothly, but when it running for the second one I got a following error:

```
Failed authorization procedure. <mydomain> (http-01): urn:ietf:params:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://<mydomain>/.well-known/acme-challenge/VaCGMLcnszmYVc6afGPJbGwUS2SjuKhWABLcCv2HZkM: Connection refused
```

**Comment by moritzschaefer** [comment]
do a PR <3

**Comment by adespain** [comment]
I also like this solution!  I apologize if you get an email for some domains I was testing @dchersey i forgot to change the address before I ran it.  However with your updated script I am getting: 
```
req: Can't open "/etc/letsencrypt/live/domain-example.com/privkey.pem" for writing, No such file or directory
```
for each of the domains, do you know why i get that error?

**Comment by vesamet** [comment]
Same for me. I also got `req: Can't open "/etc/letsencrypt/live/domain-example.com/privkey.pem" for writing, No such file or directory`

**Comment by radusuciu** [comment]
Both the current and this modified init script just hang for me when getting dummy certs..

**Comment by hodgef** [comment]
This worked for me. Thanks! I hope this is merged soon as the code on master is broken for multiple domains

**Comment by vesamet** [comment]
I don't think it will, since the maintainer doesn't seem to focus on this script for the last few months

**Comment by wmnnd** [comment]
Hey everyone, thank you for your patience!
The new [2.x](https://github.com/wmnnd/nginx-certbot/tree/2.x) branch now makes it much easier to specify multiple domains. You can now call the script like this to initialize it with multiple domains: `./init-letsencrypt.sh -d domain1.org -d domain2.org` :tada:
