### ISSUE TITLE
[Support] Challenge failed for domain docker.xyz.com

### ISSUE THREAD

**Issue by abhilashshettigar** [wmnnd/nginx-certbot#63]
Steps Which I performed 
1. Create a new instance 
2. Added IP of that instance to A record
3. Opened ports for 80,22,443
4. Cloned project 
5. installed docker and docker-compose 
6. Ran ./init-letsencrypt.sh file
7. throws error `Challenge failed for domain docker.xyz.com`

please guide I am stuck here and do let me know for any of your findings

**Comment by abhilashshettigar** [comment]
What I found that, suppose I manually install Nginx and hit the Url then I am able to see the Nginx default page

**Comment by thomasneuteboom** [comment]
I've got the same problem. I'm running on a clean VPS with Docker installed, using this repository exclusively to test.

I've made a 'test' file using `echo test >> index.html` within `./data/certbot/www` to test `http://***.com/.well-known/acme-challenge/test` which seems to be working fine.

**error running `./init-letsencrypt.sh`:**
```
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: ***.com
   Type:   unauthorized
   Detail: Invalid response from
   http://***.com/.well-known/acme-challenge/_nj6tMpsn9POrHsXoa91UqPcpldhEB0pb88KuMN3_sM
   [2a02:2268:ffff:ffff::4]: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD
   HTML 2.0//EN\">\n<html><head>\n<title>404 Not
   Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.
```

**app.conf:**
```
server {
    listen 80;
    server_name ***.com;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name ***.com;
    server_tokens off;

    ssl_certificate /etc/letsencrypt/live/***.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/***.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass  http://***.com;
        proxy_set_header    Host                $http_host;
        proxy_set_header    X-Real-IP           $remote_addr;
        proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
    }
}
```

Did you make any progress @abhilashshettigar?

**Comment by abhilashshettigar** [comment]
Feels Like a moron, that I didn't opened the port which was mandatory for SSL i.e 443
hell yeah it worked smoothly 
thanks @wmnnd for such wonderful boilerplate
