### ISSUE TITLE
Is there a way to config like *.domian.com?

### ISSUE THREAD

**Issue by bryht** [wmnnd/nginx-certbot#67]
![image](https://user-images.githubusercontent.com/2418508/79166905-7198a280-7de6-11ea-86f5-613482524cd8.png)

got an error like this, any idea how to use the plugin?

**Comment by kevincoakley** [comment]
I believe this example uses Let's Encrypt HTTP-01 challenge type. In order for Let's Encrypt to issue wildcard certs, the DNS-01 challenge type is required. 

The DNS-01 challenge type is more complex and requires a DNS provider that provide a supported API. There is a list of supported DNS providers and some code to integrate with them at https://community.letsencrypt.org/t/dns-providers-who-easily-integrate-with-lets-encrypt-dns-validation/86438 . 


```
Additionally, wildcard domains must be validated using the DNS-01 challenge type. 
This means that you’ll need to modify DNS TXT records in order to demonstrate 
control over a domain for the purpose of obtaining a wildcard certificate.
```

https://community.letsencrypt.org/t/acme-v2-and-wildcard-certificate-support-is-live/55579

**Comment by bryht** [comment]
> I believe this example uses Let's Encrypt HTTP-01 challenge type. In order for Let's Encrypt to issue wildcard certs, the DNS-01 challenge type is required.
> 
> The DNS-01 challenge type is more complex and requires a DNS provider that provide a supported API. There is a list of supported DNS providers and some code to integrate with them at https://community.letsencrypt.org/t/dns-providers-who-easily-integrate-with-lets-encrypt-dns-validation/86438 .
> 
> ```
> Additionally, wildcard domains must be validated using the DNS-01 challenge type. 
> This means that you’ll need to modify DNS TXT records in order to demonstrate 
> control over a domain for the purpose of obtaining a wildcard certificate.
> ```
> 
> https://community.letsencrypt.org/t/acme-v2-and-wildcard-certificate-support-is-live/55579

Thank you for the tips, following it got some help.
https://medium.com/@saurabh6790/generate-wildcard-ssl-certificate-using-lets-encrypt-certbot-273e432794d7
![image](https://user-images.githubusercontent.com/2418508/80861807-0f0e2600-8c71-11ea-82b1-2b67f475c40e.png)
