### ISSUE TITLE
Dummy key size is too small

### ISSUE THREAD

**Issue by nick-parker** [wmnnd/nginx-certbot#73]
I haven't tracked down when this was introduced, but the [tutorial](https://medium.com/@pentacent/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71) is currently broken because the generated dummy key is 1024 bit and nginx gives a 'key too small' error. Probably that parameter should just reference the rsa_key_size variable so they stay in sync.

It'd also be nice if there was some logic to check the nginx container didn't crash before the challenges are attempted, this took me a bit to diagnose.

**Comment by wmnnd** [comment]
Thanks for reporting this, this has been fixed via #72 :+1:
