### ISSUE TITLE
- ./data/nginx:/etc/nginx/conf.d

### ISSUE THREAD

**Issue by sebdanielsson** [wmnnd/nginx-certbot#93]
Changing the local path of the conf.d directory containing the app.conf file to it's own conf dir under nginx would make the structure more consistent with the other directories. It would also be a cleaner way to add some flexibility, for example you could put nginx.conf inside ./data/nginx/conf/nginx.conf and bind mount it straight to /etc/nginx/nginx.conf insted of having it being put to /etc/nginx/conf.d/nginx.conf like it does today.

Today:
volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

New proposal:
volumes:
      - ./data/nginx/conf/conf.d:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

**Comment by samcov** [comment]
This makes a LOT more sense to me, it's just wiser to stick with the known locations of things because I'm struggling with your conf.d & app.conf differences.
